name: traffic-fatalities
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - jupyterlab=4.0
  - notebook=7.0
  - ipykernel=6.29
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.8
  - seaborn=0.13
  - scipy=1.13
  - statsmodels=0.14
  - scikit-learn=1.4
  - shapely=2.0
  - geopandas=0.14
  - pyproj=3.6
  - folium=0.16
  - branca=0.7
  - tqdm=4.66
  - pip
